# Generated by Django 2.0.1 on 2018-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='memo',
        ),
    ]
