# Generated by Django 2.0.1 on 2018-01-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180126_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
