# Generated by Django 2.0.1 on 2018-01-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180127_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
